export const GALLERY_PHOTOS = [
  { src: "/images/gallery/job-01.jpg", alt: "Eufy Security fingerprint and keypad deadbolt installed on a black door" },
  { src: "/images/gallery/job-02.jpg", alt: "Car key fob held next to a red Toyota hatchback parked at the curb" },
  { src: "/images/gallery/job-03.jpg", alt: "Programming a smart key fob for a gray Jeep Grand Cherokee SUV" },
  { src: "/images/gallery/job-04.jpg", alt: "Replacement key fob for a silver Toyota Prius held next to the car" },
  { src: "/images/gallery/job-05.jpg", alt: "Car remote key held near the rear of a white SUV at night" },
  { src: "/images/gallery/job-06.jpg", alt: "Rekeying a Schlage keypad deadbolt on a black door" },
  { src: "/images/gallery/job-07.jpg", alt: "Cutting a new key on a 2-in-1 pick tool with an extracted door lock cylinder" },
  { src: "/images/gallery/job-08.jpg", alt: "Deadbolt and knob lock cylinders on a dark door, viewed from inside" },
  { src: "/images/gallery/job-09.jpg", alt: "Rekeyed Schlage electronic keypad deadbolt on a dark door" },
  { src: "/images/gallery/job-10.jpg", alt: "Replacement key fob for a silver Toyota Tacoma truck in the rain" },
  { src: "/images/gallery/job-11.jpg", alt: "Two replacement key fobs for a gray Lexus ES sedan" },
  { src: "/images/gallery/job-12.jpg", alt: "Replacement key fob for a white Ford Transit Connect van" },
  { src: "/images/gallery/job-13.jpg", alt: "Two Jeep Compass key fobs held in front of a white Jeep SUV" },
  { src: "/images/gallery/job-14.jpg", alt: "Business card viewed through a door peephole after cylinder replacement" },
  { src: "/images/gallery/job-15.jpg", alt: "Yale electronic keypad deadbolt with keyed cylinder on a white door" },
  { src: "/images/gallery/job-16.jpg", alt: "Schlage keypad lever lock with keyed cylinder on a white door" },
  { src: "/images/gallery/job-17.jpg", alt: "Rekeyed deadbolt on a wrought iron gate with keypad-style scrollwork" },
  { src: "/images/gallery/job-18.jpg", alt: "Combination push-button lock on a gray commercial door" },
  { src: "/images/gallery/job-19.jpg", alt: "Schlage keyless touchpad deadbolt with keyhole override on a white door" },
  { src: "/images/gallery/job-20.jpg", alt: "Electronic keypad combination lock on a commercial floor safe" },
  { src: "/images/gallery/job-21.jpg", alt: "Lockly smart deadbolt with touchscreen keypad and key override on a door" },
  { src: "/images/gallery/job-22.jpg", alt: "Polished brass door knob and deadbolt handleset on a maroon front door" },
  { src: "/images/gallery/job-23.jpg", alt: "Brass entry door handleset with deadbolt and lever on a red door" },
  { src: "/images/gallery/job-24.jpg", alt: "Electronic keypad lock and mortise latch installed on a wood door edge" },
  { src: "/images/gallery/job-25.jpg", alt: "Rekeyed deadbolt with locked indicator on a black storefront door frame" },
  { src: "/images/gallery/job-26.jpg", alt: "Electronic keypad lock mechanism exposed inside a SentrySafe security cabinet" },
  { src: "/images/gallery/job-27.jpg", alt: "Replacement key fob held near a silver Toyota Camry hybrid" },
  { src: "/images/gallery/job-28.jpg", alt: "Silver Toyota Camry parked on a residential street with replacement key fob" },
  { src: "/images/gallery/job-29.jpg", alt: "Mortise lock mechanism removed from a commercial glass door for rekeying" },
  { src: "/images/gallery/job-30.jpg", alt: "Rekeyed deadbolt and door lever installed on a dark commercial door" },
  { src: "/images/gallery/job-31.jpg", alt: "Picking a USPS cluster mailbox lock with a 2-in-1 pick tool" },
  { src: "/images/gallery/job-32.jpg", alt: "Bypassing a small electronic keypad safe lock with a pick and extractor tool" },
  { src: "/images/gallery/job-33.jpg", alt: "Interior mortise lock hardware removed from an antique brass door lock" },
  { src: "/images/gallery/job-34.jpg", alt: "Schlage keypad deadbolt with lever handle on a dark wood door" },
  { src: "/images/gallery/job-35.jpg", alt: "Close-up of a scratched key-in-knob lock cylinder face" },
  { src: "/images/gallery/job-36.jpg", alt: "Schlage keyless entry lever lock installed on a light-colored door" },
  { src: "/images/gallery/job-37.jpg", alt: "Antique glass door knob with mortise lock and skeleton keyhole on a white door" },
  { src: "/images/gallery/job-38.jpg", alt: "Kwikset deadbolt and door lever lock set on a wood front door" },
  { src: "/images/gallery/job-39.jpg", alt: "Baldwin deadbolt and lever handle with electronic access reader on a red door" },
  { src: "/images/gallery/job-40.jpg", alt: "Opened SentrySafe fire safe with borescope camera and tools used to access it" },
  { src: "/images/gallery/job-41.jpg", alt: "Baldwin deadbolt and brass entry handleset installed on a wood door" },
  { src: "/images/gallery/job-42.jpg", alt: "Combination dial and key lock mechanism on a Sentry safe door" },
];
